import type { RuntimeMessage, RuntimeProvider, RuntimeProviderResponse, RuntimeToolCall } from "../runtime/index.js";

export interface FakeProviderOptions {
  readonly defaultResponse?: string;
}

export function createFakeProvider(options: FakeProviderOptions = {}): RuntimeProvider {
  const defaultResponse = options.defaultResponse ?? "Safe fake-provider response. No network or credentials were used.";

  return async (request): Promise<RuntimeProviderResponse> => {
    const lastMessage = request.messages.at(-1);

    if (lastMessage?.role === "tool") {
      return { content: summarizeToolMessage(lastMessage) };
    }

    const prompt = readLastUserPrompt(request.messages).toLowerCase();
    const toolCall = createDemoToolCall(prompt);

    if (toolCall !== undefined) {
      return {
        content: "",
        toolCalls: [toolCall]
      };
    }

    return { content: defaultResponse };
  };
}

function readLastUserPrompt(messages: readonly RuntimeMessage[]): string {
  return [...messages].reverse().find((message) => message.role === "user")?.content ?? "";
}

function createDemoToolCall(prompt: string): RuntimeToolCall | undefined {
  if (prompt.includes("list")) {
    return {
      id: "fake-call-list",
      name: "list",
      arguments: { path: ".", maxDepth: 2, maxEntries: 50 }
    };
  }

  if (prompt.includes("readme") || prompt.includes("read")) {
    return {
      id: "fake-call-read",
      name: "read",
      arguments: { path: "README.md", maxBytes: 20_000 }
    };
  }

  if (prompt.includes("search")) {
    return {
      id: "fake-call-search",
      name: "search",
      arguments: { path: ".", query: "policy", maxResults: 10 }
    };
  }

  if (prompt.includes("bash") || prompt.includes("shell")) {
    return {
      id: "fake-call-bash",
      name: "bash",
      arguments: { command: "echo safe-demo" }
    };
  }

  if (prompt.includes("write")) {
    return {
      id: "fake-call-write",
      name: "write",
      arguments: { path: "demo-output.txt", content: "Generated by fake provider.\n" }
    };
  }

  return undefined;
}

function summarizeToolMessage(message: RuntimeMessage): string {
  let parsed: unknown;

  try {
    parsed = JSON.parse(message.content) as unknown;
  } catch {
    return `Tool ${message.name ?? "unknown"} completed.`;
  }

  if (!isObject(parsed)) {
    return `Tool ${message.name ?? "unknown"} completed.`;
  }

  const status = typeof parsed["status"] === "string" ? parsed["status"] : "unknown";
  const name = typeof parsed["name"] === "string" ? parsed["name"] : message.name ?? "unknown";
  return `Tool ${name} finished with status ${status}.`;
}

function isObject(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
